import {clamp,dist,eye,blastUnsafe,walkEdge,floorAt,obstructed,nearest} from './core.mjs';
import {POWERUPS,WEAPONS,RULES} from './data.mjs';
import {modeWeapon,teamMode} from './config.mjs';
import {harnessBotHints,preferredHarnessWeapon} from './harness-profiles.mjs';
import {operatorProfile,preferredOperatorWeapon} from './operator-profiles.mjs';
import {botBehavior,botWeaponBandPick} from './bot-personalities.mjs';
import {enemyBehavior} from './enemy-types.mjs';
import {turnToward} from './character-anim.mjs';
import {payloadPosition} from './payload.mjs';
import {vehicleSeatFor,vehicleMounted} from './vehicles.mjs';
const v=(x=0,y=0,z=0)=>({x,y,z});
const norm=a=>{const l=Math.hypot(a.x,a.y,a.z)||1;return v(a.x/l,a.y/l,a.z/l)};
export function defensivePost(match,a){const base=match.flagSpawns[a.team]||[match.center.x,match.center.z],dx=match.center.x-base[0],dz=match.center.z-base[1],length=Math.hypot(dx,dz)||1,distance=Math.min(12,length*.35),x=base[0]+dx/length*distance,z=base[1]+dz/length*distance;return {x,y:floorAt(x,z,match.arena)??0,z};}

export function flankDestination(match,a,enemy){const b=a.bot,nodes=match.nav?.length?match.nav:null;if(b.flank&&!b.flankDone){if(dist(a,b.flank)<7)b.flankDone=true;else return b.flank;}if(b.flankDone||!nodes)return {x:enemy.x,y:enemy.y??0,z:enemy.z};const candidates=nodes.map(n=>({n,s:dist(a,n)+Math.hypot(n.x-enemy.x,n.z-enemy.z)})).sort((p,q)=>p.s-q.s).slice(0,3),pick=candidates[a.id%candidates.length]?.n;if(!pick||dist(a,pick)<8)return {x:enemy.x,y:enemy.y??0,z:enemy.z};b.flank={x:pick.x,y:Number.isFinite(pick.y)?pick.y:(floorAt(pick.x,pick.z,match.arena)??0),z:pick.z};return b.flank;}

export function patrolPoint(match,a){const nodes=match.nav?.length?match.nav:null;if(nodes){const start=a.bot.patrol||0,index=(start+1)%nodes.length;let chosen=null;for(let i=0;i<nodes.length;i++){const n=nodes[(index+i)%nodes.length];if(Math.hypot(n.x-a.x,n.z-a.z)>8){chosen=n;a.bot.patrol=(index+i+1)%nodes.length;break;}}if(!chosen){a.bot.patrol=index;chosen=nodes[index];}return {x:chosen.x,y:Number.isFinite(chosen.y)?chosen.y:(floorAt(chosen.x,chosen.z,match.arena)??0),z:chosen.z};}const p=match.pickups.find(p=>!p.wait&&dist(a,p)>6)||match.pickups[0];return p?{x:p.x,y:p.y,z:p.z}:{x:match.center.x,y:floorAt(match.center.x,match.center.z,match.arena)??0,z:match.center.z};}

export function separation(match,a,radius=2.6){let x=0,z=0;for(const other of match.actors){if(other===a||other.health<=0)continue;const dx=a.x-other.x,dz=a.z-other.z,d=Math.hypot(dx,dz);if(d>1e-4&&d<radius){const weight=(radius-d)/radius;x+=dx/d*weight;z+=dz/d*weight;}}return {x,z};}

export function spreadBias(match,a,point){const h=(Math.imul((a.id|0)+1,73856093)^Math.imul(Math.round((point.x||0)*10),19349663)^Math.imul(Math.round((point.z||0)*10),83492791))>>>0;return (h%997)/997;}

export function zoneSlot(match,a,zone,team){const n=8,index=((a.id%n)+n)%n,defending=zone.owner===team,centerY=()=>Number.isFinite(zone.y)?zone.y:(floorAt(zone.x,zone.z,match.arena)??0),safe=(x,z)=>{const y=floorAt(x,z,match.arena);return y!==null&&!obstructed(x,y,z,RULES.radius*.9,match.arena)?{x,y,z}:null;};let candidate;if(defending){const angle=(index/n)*Math.PI*2+(a.id%3)*.35,radius=Math.max(1.2,(zone.radius||3.5)*.6);candidate={x:zone.x+Math.cos(angle)*radius,z:zone.z+Math.sin(angle)*radius};}else{const pool=teamMode(match.config)&&team!==undefined?match.teamSpawns[team]:match.spawns,spawn=pool[index%pool.length],sx=Array.isArray(spawn)?spawn[0]:spawn.x,sz=Array.isArray(spawn)?spawn[1]:spawn.z,angle=Math.atan2(sz-zone.z,sx-zone.x),spread=(index/n)*Math.PI*1.5-Math.PI*.75,radius=Math.max(1,(zone.radius||3.5)*.55);candidate={x:zone.x+Math.cos(angle+spread)*radius,z:zone.z+Math.sin(angle+spread)*radius};}const point=safe(candidate.x,candidate.z);if(point)return {x:point.x,y:point.y,z:point.z};const center=safe(zone.x,zone.z);if(center)return {x:center.x,y:center.y,z:center.z};let best=null,bestD=Infinity;for(const node of match.nav||[]){const d=Math.hypot(node.x-zone.x,node.z-zone.z),limit=(zone.radius||3.5)+5;if(d>limit||d>=bestD)continue;const spot=safe(node.x,node.z);if(spot){best={x:spot.x,y:spot.y,z:spot.z};bestD=d;}}if(best)return best;for(let ring=1;ring<=4;ring++)for(let i=0;i<n;i++){const ang=(i/n)*Math.PI*2,rad=(zone.radius||3.5)+ring,spot=safe(zone.x+Math.cos(ang)*rad,zone.z+Math.sin(ang)*rad);if(spot)return {x:spot.x,y:spot.y,z:spot.z};}return {x:zone.x,y:centerY(),z:zone.z};}

export function zoneDefense(match,a,owned){if(!owned.length)return null;const mates=match.actors.filter(o=>o.health>0&&o.team===a.team);for(const z of owned){if(match.actors.some(o=>o!==a&&o.health>0&&o.team===a.team&&Math.hypot(o.x-z.x,o.z-z.z)<=z.radius))continue;const mine=Math.hypot(a.x-z.x,a.z-z.z);let closest=true;for(const o of mates){if(o!==a&&Math.hypot(o.x-z.x,o.z-z.z)<mine){closest=false;break;}}if(closest)return z;}return null;}

export function botInput(match,a,dt){const b=a.bot,hints=harnessBotHints(a.harness)||{range:[6,16],retreatHealth:.4,power:'hurt'},operator=operatorProfile(a.character),behavior=a.npcType?enemyBehavior(a):botBehavior(a);b.behavior=behavior;const retreatAt=clamp(behavior.retreat*.6+(hints.retreatHealth??.4)*.4,.12,.75);b.think-=dt;b.memory=Math.max(0,b.memory-dt);b.suppressed=Math.max(0,(b.suppressed||0)-dt);b.vehicleCooldown=Math.max(0,(b.vehicleCooldown||0)-dt);b.reaction=Math.max(0,b.reaction-dt);if(a.traversalFlight||a.zipRide)return {};if(a.vehicleId!==null&&a.vehicleSeat==='passenger')return {interact:true};if(a.vehicleId!==null&&a.vehicleSeat==='gunner'){const mounted=match.vehicleById(a.vehicleId);if(!mounted||mounted.driver===null)return {interact:true};}const ride=a.vehicleId===null&&(b.vehicleCooldown||0)<=0&&behavior.vehicle>.32?match.vehicles.find(vehicle=>{const seat=vehicleSeatFor(vehicle);return seat&&seat.role!=='passenger'&&Math.hypot(a.x-vehicle.position.x,a.z-vehicle.position.z)<2.4&&Math.abs(a.y-vehicle.position.y)<(vehicle.config?.flight===true?3.2:2.4);}):null;if(ride&&!match.flagCarrier(a))return {interact:true};
    if(b.think<=0){b.think=clamp((match.difficulty.think+match.random()*.15)*(behavior.thinkScale||1),match.difficulty.think*.6,(match.difficulty.think+.15)*1.4);const candidates=match.actors.filter(t=>t!==a&&t.health>0&&dist(a,t)<(a.botScan||25)&&match.visible(eye(a),eye(t))&&(!(t.powerups?.cloak>0)||dist(a,t)<4)&&(!teamMode(match.config)||t.team!==a.team)),locks=new Map();for(const ally of match.actors)if(ally!==a&&ally.bot&&Number.isInteger(ally.bot.target)&&ally.bot.target>=0)locks.set(ally.bot.target,(locks.get(ally.bot.target)||0)+1);const ranked=candidates.map(t=>{let score=dist(a,t)+match.random()*1.5+(locks.get(t.id)||0)*(2+behavior.hold*7);if(behavior.personality==='opportunist')score+=(t.health||100)*.14;if(behavior.role==='ambusher')score+=Math.max(0,dist(a,t)-9)*1.5;if(behavior.hold>.7)score+=Math.max(0,behavior.range[1]-dist(a,t))*.4;if(behavior.archetype==='flanker')score+=Math.max(0,dist(a,t)-9)*.25;else if(behavior.archetype==='sharpshooter')score-=Math.min(dist(a,t),26)*.06;else if(behavior.archetype==='rusher')score-=Math.max(0,9-dist(a,t))*.18;else if(behavior.archetype==='defender')score+=Math.max(0,dist(a,t)-13)*.22;else if(behavior.archetype==='support')score+=(t.health||100)*.06;return {t,score};}).sort((c,d)=>c.score-d.score),target=ranked.length?ranked[0].t:null;if(target){if(b.target!==target.id)b.reaction=match.difficulty.reaction+match.random()*.25;b.target=target.id;b.memory=1.5;b.seen={x:target.x,y:target.y,z:target.z};}else if(!b.memory)b.target=-1;
    const criticalHealth=a.health<a.maxHealth*retreatAt,objectiveMode=['ctf','koth','domination','teamdeathmatch','assault','combined-arms','payload'].includes(match.config.mode),supply=objectiveMode?undefined:match.pickups.filter(p=>!p.wait&&match.useful(a,p)&&(walkEdge(a,p,match.arena)||path(a,p,match.nav,match.edges).length>1)).sort((c,d)=>(dist(a,c)+match.spreadBias(a,c)*4*behavior.supply-(c.kind==='health'&&a.health<a.maxHealth*.55?20:0))-(dist(a,d)+match.spreadBias(a,d)*4*behavior.supply-(d.kind==='health'&&a.health<a.maxHealth*.55?20:0)))[0],healthSupply=objectiveMode?match.pickups.filter(p=>!p.wait&&p.kind==='health'&&match.useful(a,p)&&dist(a,p)<=8&&(walkEdge(a,p,match.arena)||path(a,p,match.nav,match.edges).length>1)).sort((c,d)=>dist(a,c)-dist(a,d))[0]:undefined,strategicSupply=objectiveMode?match.pickups.filter(p=>!p.wait&&match.useful(a,p)&&(p.kind==='armor'||POWERUPS.some(power=>power.id===p.kind))&&dist(a,p)<=3&&walkEdge(a,p,match.arena)).sort((c,d)=>dist(a,c)-dist(a,d))[0]:undefined,needs=objectiveMode?(criticalHealth&&healthSupply||strategicSupply):(supply&&(criticalHealth||(a.ammo.slice(1).every(n=>n===0)&&supply.kind!=='health')||(a.health<a.maxHealth*.7&&supply.kind==='health')));
     const duel=behavior.objective<.4&&target&&b.target>=0&&b.memory>0&&!needs;
     if(match.config.mode==='ctf'){const carrying=Object.values(match.flags).some(f=>f.carrier===a.id),enemy=match.flags[1-a.team],own=match.flags[a.team],enemyDistance=dist(a,enemy),ownDistance=dist(a,own);if(carrying){b.state='flag-return';b.destination={x:own.x,y:0,z:own.z};}else if(needs){b.state='seek';b.destination=objectiveMode?needs:supply;}else if(behavior.hold>.62&&own.state!=='at-base'){b.state='flag-defend';b.destination={x:own.x,y:0,z:own.z};}else if((own.state==='dropped'||own.carrier!==null)&&(ownDistance<=enemyDistance||behavior.hold>.62)){b.state='flag-defend';b.destination={x:own.x,y:0,z:own.z};}else if(enemy.state==='carried'){b.state='flag-defend';b.destination=match.defensivePost(a);}else{b.state='flag-attack';b.destination=enemyDistance>38||behavior.flank>.7?match.flankDestination(a,enemy):{x:enemy.x,y:0,z:enemy.z};}}else if(needs){b.state='seek';b.destination=objectiveMode?needs:supply;}else if((match.config.mode==='koth'||match.config.mode==='domination'||match.config.mode==='combined-arms')&&match.objectiveState&&!duel){const zones=match.objectiveState.zones,owned=zones.filter(z=>z.owner===a.team),enemyZones=zones.filter(z=>z.owner!==a.team),holdZone=behavior.hold>.62&&owned.length?owned.slice().sort((x,y)=>dist(a,x)-dist(a,y))[0]:null,defendZone=match.zoneDefense(a,owned),pushPool=enemyZones.length?enemyZones:zones,pushZone=pushPool.slice().sort((x,y)=>dist(a,x)-dist(a,y))[0],zone=defendZone||holdZone||pushZone;b.state='objective';b.destination=match.zoneSlot(a,zone,a.team);}else if(match.config.mode==='assault'&&match.objectiveState&&!duel){const sectors=match.objectiveState.sectors||[],active=sectors[Math.min(match.objectiveState.active??0,Math.max(0,sectors.length-1))];if(active){const defending=a.team===(match.objectiveState.defender??1);b.state=defending?'hold':'objective';b.destination=defending?match.zoneSlot(a,{...active,owner:a.team},a.team):match.zoneSlot(a,active,a.team);}else b.state='roam';}else if(match.config.mode==='payload'&&match.objectiveState&&!duel){const st=match.objectiveState,pos=st.position??payloadPosition(st),attacking=a.team===(st.attacker??0);b.state=attacking?'objective':'hold';b.destination=attacking?match.zoneSlot(a,{id:'payload',x:pos.x,z:pos.z,y:pos.y,radius:st.radius,owner:a.team},a.team):{x:pos.x,y:pos.y,z:pos.z};}else if(target){if(behavior.flank>.65&&dist(a,target)>12){b.state='flank';b.destination=match.flankDestination(a,target);}else if(behavior.hold>.72&&dist(a,target)>16){b.state='hold';b.destination=match.defensivePost(a);}else{b.state='engage';b.destination={x:target.x,y:target.y,z:target.z};}}else if(b.memory){b.state='pursue';b.destination=b.seen;}else{b.state='roam';if(!b.destination||dist(a,b.destination)<2.5)b.destination=match.patrolPoint(a);}
 if(a.vehicleId===null&&(b.vehicleCooldown||0)<=0&&b.destination&&!match.flagCarrier(a)&&dist(a,b.destination)>30){const rig=match.vehicles.find(vehicle=>{const seat=vehicleSeatFor(vehicle);return seat&&seat.role!=='passenger'&&!vehicleMounted(vehicle,a.id)&&Math.hypot(a.x-vehicle.position.x,a.z-vehicle.position.z)<16&&Math.abs(a.y-vehicle.position.y)<(vehicle.config?.flight===true?20:4);});if(rig)b.destination={x:rig.position.x,y:rig.position.y,z:rig.position.z};}
  if(b.destination){b.route=path(a,b.destination,match.nav,match.edges);if(b.route.length>1&&dist(a,match.nav[b.route[0]])<2)b.route.shift();}
  b.seeking=Boolean(needs);
  }
 const t=match.actors[b.target],canSee=t&&t.health>0&&b.memory>0&&dist(a,t)<(a.botScan||25)&&match.visible(eye(a),eye(t));const routeNode=b.route.length?match.nav[b.route[0]]:null;let dest=b.route.length>1?routeNode:(b.destination||routeNode||a);
 if(canSee&&!b.tracking)b.reaction=Math.max(b.reaction,match.difficulty.reaction+match.random()*.25);
 b.tracking=!!canSee;
  if(dist(a,dest)<.8&&b.route.length&&(b.route.length>1||walkEdge(a,b.destination||a,match.arena))){b.route.shift();dest=b.route.length?match.nav[b.route[0]]:b.destination||a;}
if(b.destination&&walkEdge(a,b.destination,match.arena))dest=b.destination;
else if(!b.route.length&&dest&&!walkEdge(a,dest,match.arena)){const node=match.nav[nearest(a,match.nav)];dest=node&&dist(a,node)>1?node:null;}
let delta=dest?v(dest.x-a.x,0,dest.z-a.z):v(0,0,0),l=Math.hypot(delta.x,delta.z);let input=l>.4?{x:delta.x/l,z:delta.z/l}:{};
  if(canSee){const d=dist(a,t),desperate=(a.health<a.maxHealth*retreatAt||b.suppressed>0)&&!b.seeking,unsafeBlast=blastUnsafe(WEAPONS[a.weapon],d),band=behavior.range,hold=behavior.hold>.62,inner=clamp(behavior.engageBand[0],band[0],band[1]),outer=clamp(behavior.engageBand[1],inner,band[1]),fresh=(hold?outer:inner+(1-behavior.aggression)*1.8)+(desperate?5:0);if(desperate||!Number.isFinite(b.standoff)||Math.abs(d-b.standoff)>1.25)b.standoff=fresh;const desired=b.standoff,closing=unsafeBlast||desperate?-1:d>desired+1?1:d<desired-1?-.7:0,toward=norm(v(t.x-a.x,0,t.z-a.z)),period=Math.max(.5,behavior.strafePeriod||2),phase=behavior.strafePhase||0;let side;if(behavior.strafePattern===1)side=Math.floor((match.time+phase)/period)%2===0?1:-1;else if(behavior.strafePattern===2)side=Math.sin((match.time+phase)*(1.6+behavior.strafe*1.4))>=0?1:-1;else side=Math.sin(match.time*(1.3+behavior.strafe)+a.id*1.7)>0?1:-1;if(b.strafeReverse>-99&&match.time-b.strafeReverse<.4)side=-side;const strafe=behavior.strafe*(behavior.aggression>.65?.85:.55),combat={x:toward.x*closing+toward.z*side*strafe,z:toward.z*closing-toward.x*side*strafe};input=l>.4&&b.state!=='engage'&&b.state!=='hold'?{x:delta.x/l+combat.x*.35,z:delta.z/l+combat.z*.35}:combat;
   const available=WEAPONS.map((w,index)=>a.ammo[index]>0?index:-1).filter(index=>index>=0),preferred=preferredHarnessWeapon(a.harness,available),operatorWeapon=preferredOperatorWeapon(a.character,available),far=behavior.range[1],bandInReach=(behavior.weaponBand==='close'&&d<12)||(behavior.weaponBand==='mid'&&d>=8&&d<=26)||(behavior.weaponBand==='long'&&d>16),bandWeapon=bandInReach?botWeaponBandPick(a.ammo,behavior.weaponBand):-1,ladderWeapon=d<8?(a.ammo[9]>0?9:a.ammo[3]>0?3:0):d>20&&a.ammo[8]>0?8:d>14&&a.ammo[2]>0?2:d>5&&d<16&&a.ammo[1]>0?1:a.ammo[7]>0?7:a.ammo[5]>0?5:a.ammo[4]>0?4:a.ammo[6]>0?6:0,rangeWeapon=bandWeapon>=0?bandWeapon:ladderWeapon; a.weapon=modeWeapon(match.config)??((match.config.mode==='armsrace'||match.config.randomLoadout===true)&&Number.isInteger(a.weapon)?a.weapon:(rangeWeapon||preferred||operatorWeapon||0));
 b.aimWait=(b.aimWait||0)-dt;
 if(b.aimWait<=0){const err=match.difficulty.error*(1+match.random()*.89)*(b.suppressed>0?1.9:1);b.aimError=v((match.random()-.5)*err,(match.random()-.5)*err,(match.random()-.5)*err);b.aimWait=match.difficulty.think;}
 const lead=WEAPONS[a.weapon].speed?d/WEAPONS[a.weapon].speed:0,dir=norm(v(t.x+t.vx*lead-a.x+d*b.aimError.x,t.y+1.1-(a.y+1.45)+d*b.aimError.y,t.z+t.vz*lead-a.z+d*b.aimError.z));
 const turn=match.difficulty.id==='easy'?2.5:match.difficulty.id==='normal'?4:8,yaw=Math.atan2(-dir.x,-dir.z),pitch=Math.asin(dir.y),deltaYaw=Math.atan2(Math.sin(yaw-a.yaw),Math.cos(yaw-a.yaw));
 a.yaw+=clamp(deltaYaw,-turn*dt,turn*dt);a.pitch+=clamp(pitch-a.pitch,-turn*dt,turn*dt);
   if(!behavior.meleeOnly&&!b.reaction&&!unsafeBlast&&a.vehicleId===null&&Math.abs(deltaYaw)<.2&&Math.abs(pitch-a.pitch)<.2)match.fire(a);if(!behavior.meleeOnly&&a.vehicleId===null&&(a.grenadeCooldown||0)<=0&&a.grounded&&d>7&&d<20)match.throwGrenade(a);if(d<=(behavior.meleeRange||2.2)&&!a.melee)input.melee=true;
   const nearby=match.actors.filter(enemy=>enemy!==a&&enemy.health>0&&(!teamMode(match.config)||enemy.team!==a.team)&&dist(a,enemy)<(hints.range[1]||16)).length,shouldPower=hints.power==='close'?d<4.5:hints.power==='escape'?d>8:hints.power==='visible'?d<far&&a.ammo[a.weapon]>2:hints.power==='hurt'?a.health<a.maxHealth*retreatAt:hints.power==='approach'?d>9:hints.power==='cluster'?(d<7||nearby>1):d<far;
   if(!a.cooldown&&shouldPower)match.power(a);
 }else if(l>.2){const roamTurn=(match.difficulty.id==='easy'?2.5:match.difficulty.id==='normal'?4:8);a.yaw=turnToward(a.yaw,Math.atan2(-delta.x,-delta.z),roamTurn*dt);}
 const sep=a.grounded?match.separation(a,behavior.spacing):{x:0,z:0};if(sep.x||sep.z){input.x=(input.x||0)+sep.x*.95;input.z=(input.z||0)+sep.z*.95;}const inputLength=Math.hypot(input.x||0,input.z||0);if(inputLength>1e-4){input.x/=inputLength;input.z/=inputLength;}
const postured=Math.hypot(input.x||0,input.z||0)>.1;if(postured){input.sprint=!a.crouching&&(!canSee||dist(a,canSee?t:(b.destination||a))>22);if(!canSee&&a.health<a.maxHealth*retreatAt&&a.grounded&&(a.slideCooldown||0)<=0&&Math.hypot(a.vx||0,a.vz||0)>6)input.crouch=true;}if(canSee&&!input.sprint){const range=dist(a,t);input.ads=range>9&&range<34&&(a.ammo?.[a.weapon]??0)>0;}
 b.stuck+=dt;if(b.stuck>1.3){if(dist(a,b.last)<.35){b.route=[];b.destination=match.nav[Math.floor(match.random()*match.nav.length)];b.recover=.6;b.think=0;}b.last=v(a.x,a.y,a.z);b.stuck=0;}
 if(b.recover>0){b.recover-=dt;input={x:Math.sin(a.id*2+match.time),z:Math.cos(a.id*2+match.time),jump:true};}
 if(match.arena.voidY!==undefined&&b.recover<=0&&a.grounded&&a.vehicleId===null&&(input.x||input.z)){const len=Math.hypot(input.x,input.z)||1;if(floorAt(a.x+input.x/len*.9,a.z+input.z/len*.9,match.arena)===null)input={};}
 if(match.arena.voidY!==undefined&&!a.grounded&&a.vy<0&&a.vehicleId===null&&floorAt(a.x,a.z,match.arena)===null){const node=match.nav[nearest(a,match.nav)];if(node){const dx=node.x-a.x,dz=node.z-a.z,l=Math.hypot(dx,dz)||1;input={x:dx/l,z:dz/l};}}
 return input;}

export function path(a,b,nodes,edges){const from=nearest(a,nodes),to=nearest(b,nodes),queue=[from],prev=new Map([[from,-1]]);for(let head=0;head<queue.length;head++){const n=queue[head];if(n===to)break;for(const j of edges[n])if(!prev.has(j)){prev.set(j,n);queue.push(j);}}if(!prev.has(to))return [from];const route=[];for(let n=to;n!==-1;n=prev.get(n))route.unshift(n);return route;}
