// Offline, deterministic tests for the generated material variants and the
// pure runtime accessors. No network, no timers, no random sources.

import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { MOTH_VARIANTS } from './moth-variants.mjs';
import {
  ALGORITHM,
  KINDS,
  MODULE_BUDGET_BYTES,
  VARIANT_IDS,
  buildModule,
  contrastCorrelation,
  decodePng,
  inputDigest,
  meanLuma,
  resampleWrap,
  resolveSources,
  seamMetric,
  writeModuleAtomic,
} from '../scripts/moth-variants.mjs';
import {
  configureMothVariants,
  mothVariantFor,
  mothVariantKinds,
  mothVariantNames,
  mothVariantRecord,
  mothVariantStatus,
  resetMothVariants,
} from './moth-variants-runtime.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '..');
const MODULE_PATH = path.join(HERE, 'moth-variants.mjs');
const TMP_DIR = '/tmp/opencode/moth-variants-test';

const decode = (b64) => new Uint8Array(Buffer.from(b64, 'base64'));

function withAlphaChecked(record, label) {
  assert.ok(record, `${label}: record present`);
  assert.equal(record.data.length, record.width * record.height * 4, `${label}: RGBA length`);
  for (let i = 3; i < record.data.length; i += 4) {
    if (record.data[i] !== 255) assert.fail(`${label}: alpha hole at byte ${i}`);
  }
}

test('committed module is a byte-stable generator run inside the byte budget', () => {
  const committed = fs.readFileSync(MODULE_PATH, 'utf8');
  const committedBytes = fs.statSync(MODULE_PATH).size;
  assert.ok(committed.startsWith('// GENERATED by scripts/moth-variants.mjs'), 'generated header');
  assert.ok(committed.includes('do not edit by hand'), 'do not edit warning');
  assert.ok(committed.includes(`Algorithm: ${ALGORITHM}`), 'algorithm version in header');
  assert.ok(committed.includes(`Byte budget: ${MODULE_BUDGET_BYTES} bytes`), 'byte budget in header');
  assert.ok(committedBytes < MODULE_BUDGET_BYTES, `module ${committedBytes} bytes under budget`);
  assert.ok(
    committed.includes(`this module: ${String(committedBytes).padStart(7, '0')} bytes`),
    'header states the true byte size',
  );

  const fresh = buildModule({});
  assert.equal(fresh.source, committed, 'committed module equals a fresh default generation');
  const again = buildModule({});
  assert.equal(again.source, fresh.source, 'generation is deterministic across runs');
  assert.deepEqual(MOTH_VARIANTS.kinds && Object.keys(MOTH_VARIANTS.kinds), KINDS);
});

test('recorded source digests match the archived PNG bytes', () => {
  const sources = resolveSources({});
  for (const kind of KINDS) {
    const bytes = fs.readFileSync(path.join(ROOT, sources[kind].file));
    assert.equal(MOTH_VARIANTS.sources[kind].digest, inputDigest(kind, bytes), `${kind} digest`);
    assert.equal(MOTH_VARIANTS.sources[kind].width, sources[kind].width, `${kind} source width`);
    assert.equal(MOTH_VARIANTS.sources[kind].height, sources[kind].height, `${kind} source height`);
  }
});

test('variants tile as cleanly as their source and keep dimensions/alpha', () => {
  const sources = resolveSources({});
  const tolerance = 1.15;
  for (const kind of KINDS) {
    const sourcePng = fs.readFileSync(path.join(ROOT, sources[kind].file));
    const decoded = decodePng(sourcePng);
    const size = MOTH_VARIANTS.sizes.albedo;
    const sourceTile = resampleWrap(decoded.data, decoded.width, decoded.height, size, size, 4);
    const sourceSeam = seamMetric(sourceTile, size);
    const variants = MOTH_VARIANTS.kinds[kind];
    assert.equal(variants.length, VARIANT_IDS.length, `${kind}: three variants`);
    for (const variant of variants) {
      assert.equal(variant.albedo.width, size, `${kind}/${variant.id}: albedo width`);
      assert.equal(variant.albedo.height, size, `${kind}/${variant.id}: albedo height`);
      assert.equal(variant.roughness.width, MOTH_VARIANTS.sizes.roughness, `${kind}/${variant.id}: roughness width`);
      assert.equal(variant.roughness.height, MOTH_VARIANTS.sizes.roughness, `${kind}/${variant.id}: roughness height`);
      withAlphaChecked({ ...variant.albedo, data: decode(variant.albedo.data) }, `${kind}/${variant.id} albedo`);
      withAlphaChecked({ ...variant.roughness, data: decode(variant.roughness.data) }, `${kind}/${variant.id} roughness`);
      const metric = seamMetric(decode(variant.albedo.data), size);
      assert.ok(Number.isFinite(metric.ratio), `${kind}/${variant.id}: seam ratio finite`);
      assert.ok(
        metric.ratio <= sourceSeam.ratio * tolerance + 0.1,
        `${kind}/${variant.id}: seam ${metric.ratio.toFixed(3)} vs source ${sourceSeam.ratio.toFixed(3)}`,
      );
      // Grayscale roughness: R=G=B, and its wrap step stays comparable to the
      // interior gradient (the same wrapped noise fields feed both maps).
      const rough = decode(variant.roughness.data);
      for (let i = 0; i < rough.length; i += 4) {
        if (rough[i] !== rough[i + 1] || rough[i] !== rough[i + 2]) assert.fail(`${kind}/${variant.id}: roughness not gray`);
      }
      const roughSeam = seamMetric(rough, variant.roughness.width);
      assert.ok(
        Number.isFinite(roughSeam.ratio) && roughSeam.ratio < 2,
        `${kind}/${variant.id}: roughness seam ${roughSeam.ratio.toFixed(3)}`,
      );
    }
  }
});

test('mean brightness stays within ±6% of the source and contrast is not inverted', () => {
  const sources = resolveSources({});
  for (const kind of KINDS) {
    const sourcePng = fs.readFileSync(path.join(ROOT, sources[kind].file));
    const decoded = decodePng(sourcePng);
    const size = MOTH_VARIANTS.sizes.albedo;
    const sourceTile = resampleWrap(decoded.data, decoded.width, decoded.height, size, size, 4);
    const sourceMean = meanLuma(sourceTile, size);
    for (const variant of MOTH_VARIANTS.kinds[kind]) {
      const data = decode(variant.albedo.data);
      const mean = meanLuma(data, size);
      const delta = (mean / sourceMean - 1) * 100;
      assert.ok(Math.abs(delta) <= 6, `${kind}/${variant.id}: mean delta ${delta.toFixed(2)}%`);
      // Documented contrast check: Pearson correlation of the high-pass signal
      // against the source. A negative value would mean inverted contrast.
      const correlation = contrastCorrelation(sourceTile, data, size);
      assert.ok(correlation > 0.5, `${kind}/${variant.id}: contrast correlation ${correlation.toFixed(2)}`);
    }
  }
});

test('structural kinds wear flat areas much more than seams and bolts', () => {
  const size = MOTH_VARIANTS.sizes.albedo;
  for (const kind of ['metal', 'riveted_armor']) {
    const variants = MOTH_VARIANTS.kinds[kind];
    const original = decode(variants[0].albedo.data);
    const lum = new Float32Array(size * size);
    for (let i = 0; i < lum.length; i++) lum[i] = 0.2126 * original[i * 4] + 0.7152 * original[i * 4 + 1] + 0.0722 * original[i * 4 + 2];
    const grad = new Float32Array(size * size);
    for (let y = 0; y < size; y++) {
      for (let x = 0; x < size; x++) {
        const xm = ((x - 1 + size) % size) * 4;
        const xp = ((x + 1) % size) * 4;
        const ym = ((y - 1 + size) % size) * size * 4;
        const yp = ((y + 1) % size) * size * 4;
        const row = y * size * 4;
        grad[y * size + x] =
          Math.abs(original[row + xp] - original[row + xm]) +
          Math.abs(original[yp + x * 4] - original[ym + x * 4]);
      }
    }
    const sorted = Float32Array.from(grad);
    sorted.sort();
    const q25 = sorted[Math.floor(sorted.length * 0.25)];
    const q75 = sorted[Math.floor(sorted.length * 0.75)];
    for (const variant of variants.slice(1)) {
      const data = decode(variant.albedo.data);
      let flat = 0;
      let flatN = 0;
      let structure = 0;
      let structureN = 0;
      for (let i = 0; i < size * size; i++) {
        const delta = Math.abs(0.2126 * data[i * 4] + 0.7152 * data[i * 4 + 1] + 0.0722 * data[i * 4 + 2] - lum[i]);
        if (grad[i] <= q25) { flat += delta; flatN++; }
        else if (grad[i] >= q75) { structure += delta; structureN++; }
      }
      const flatMean = flat / Math.max(flatN, 1);
      const structureMean = structure / Math.max(structureN, 1);
      assert.ok(flatMean > 0.5, `${kind}/${variant.id}: flat areas actually wear`);
      assert.ok(
        structureMean < flatMean * 0.9,
        `${kind}/${variant.id}: structural pixels protected (${structureMean.toFixed(2)} vs ${flatMean.toFixed(2)})`,
      );
    }
  }
});

test('selection is stable, distributed and bounded', () => {
  resetMothVariants();
  for (const kind of KINDS) {
    const first = mothVariantFor(kind, 'panel-17');
    assert.equal(mothVariantFor(kind, 'panel-17'), first, `${kind}: same key -> same variant`);
    assert.equal(mothVariantFor(kind, 42), mothVariantFor(kind, 42), `${kind}: numeric key stable`);
    assert.ok(mothVariantNames(kind).includes(first), `${kind}: selection is a known id`);
  }
  const seen = new Set();
  for (let i = 0; i < 600; i++) seen.add(mothVariantFor('metal', `panel-${i}`));
  assert.equal(seen.size, 3, 'sequential string keys reach all three variants');
  const seenNumbers = new Set();
  for (let i = 0; i < 600; i++) seenNumbers.add(mothVariantFor('metal', i));
  assert.equal(seenNumbers.size, 3, 'numeric keys reach all three variants');
  assert.equal(mothVariantFor('not_a_kind', 1), null, 'unknown kind -> null');
  assert.equal(mothVariantFor('metal', null), mothVariantFor('metal', ''), 'nullish keys are stable');
  assert.deepEqual(mothVariantNames('not_a_kind'), [], 'unknown names -> empty');
  assert.equal(mothVariantRecord('not_a_kind', 'original'), null, 'unknown record -> null');
});

test('runtime decodes lazily, caches identical objects and degrades to null', () => {
  const status0 = configureMothVariants();
  assert.deepEqual(status0.kinds, KINDS);
  assert.equal(status0.algorithm, ALGORITHM);
  assert.deepEqual(status0.decodedKinds, [], 'nothing decoded before first access');

  const a = mothVariantRecord('metal', 'stained');
  assert.ok(a && a.albedo && a.roughness, 'record decodes');
  assert.equal(mothVariantRecord('metal', 'stained'), a, 'decoded record is cached by identity');
  assert.equal(mothVariantRecord('metal', 0), mothVariantRecord('metal', 'original'), 'numeric index resolves');
  assert.equal(mothVariantRecord('metal', 'missing'), null, 'unknown id -> null');
  assert.equal(mothVariantRecord('rock', 'stained').albedo.data.length, MOTH_VARIANTS.sizes.albedo ** 2 * 4, 'other kinds decode');
  assert.deepEqual(mothVariantStatus().decodedKinds.sort(), ['metal', 'rock'], 'only accessed kinds decoded');

  configureMothVariants(null);
  assert.deepEqual(mothVariantKinds(), [], 'null registry -> no kinds');
  assert.deepEqual(mothVariantNames('metal'), []);
  assert.equal(mothVariantRecord('metal', 'worn'), null);
  assert.equal(mothVariantFor('metal', 'panel-1'), null, 'null registry -> fallback signal');
  assert.doesNotThrow(() => mothVariantStatus());

  resetMothVariants();
  assert.equal(mothVariantFor('rock', 'x'), mothVariantFor('rock', 'x'), 'reset restores the committed registry');
  assert.ok(mothVariantRecord('riveted_armor', 'worn').roughness.data.length > 0);
});

test('decoding also works without Buffer (browser/SSR atob path)', () => {
  const savedBuffer = globalThis.Buffer;
  try {
    globalThis.Buffer = undefined;
    configureMothVariants();
    const record = mothVariantRecord('metal', 'worn');
    assert.ok(record, 'record decodes through atob');
    assert.equal(record.albedo.data.length, MOTH_VARIANTS.sizes.albedo ** 2 * 4);
  } finally {
    globalThis.Buffer = savedBuffer;
    resetMothVariants();
  }
});

test('--only and --size keep unrelated kinds out and still produce valid variants', () => {
  const only = buildModule({ only: ['metal'], size: 32 });
  assert.deepEqual(Object.keys(only.data.kinds), ['metal'], '--only keeps other kinds out');
  assert.equal(only.summary.length, 1);
  assert.equal(only.data.sizes.albedo, 32);
  assert.equal(only.data.sizes.roughness, 16);
  fs.mkdirSync(TMP_DIR, { recursive: true });
  const target = path.join(TMP_DIR, 'metal-only.mjs');
  writeModuleAtomic(target, only.source);
  const written = fs.readFileSync(target, 'utf8');
  assert.equal(written, only.source, 'atomic write round-trips');
  assert.ok(Buffer.byteLength(written, 'utf8') < MODULE_BUDGET_BYTES);
  assert.throws(() => buildModule({ only: ['not_a_kind'], size: 32 }), /unknown kind/);
});
