'use client';
/* eslint-disable react-hooks/purity -- floating damage numbers fade against the wall clock. */
import type {ScreenProps} from '../contract';
import {Shield,Crosshair} from 'lucide-react';
import {SinglePlayerHud} from '../../game-ui/singleplayer-hud';

export function PlayingHud({ui}:ScreenProps){
 const {hud,player,display,brief,phase,hudRoute,hudMap,hudMode,isTeamMode,teamName,modeGoal,ladderStatus,flagText,armsrace,WEAPONS,activePower,powerIcon,radar,radarCols,radarBlip,crosshairGap,marker,reloadFill,reloading,posture,killNotice,suddenBanner,startBanner,scoreCue,damageIndicator,damageNumberStyle,reducedMotion,vehiclePrompt,vehicle,ammoEmpty,ammoLow,hideHud,touchControls,pointerHint,requestLock,chatOpen,isSingle,single,spectatorBoard,CAMERA_MODE_LABELS,runtime,changeMode,grenadeStatus,streakStatus,killFeedWeapon,voiceState,voiceHint,escapeHint,clock,teamScoreText,ammoText,weaponTag}=ui;
 if(!hud||!player)return null;
 const callout=!hud.spectate&&hud.killCue?hud.killCue:null;
 const kill=!hud.spectate&&killNotice&&killNotice.age<1.5?killNotice:null;
 const announcement=suddenBanner?'sudden':startBanner?'start':scoreCue?'score':callout?'callout':kill?'kill':null;
 return <div className={`game-hud${hud.spectate&&hideHud?' hide-hud':''}${touchControls&&!hud.spectate?' touch-mode':''}`}>
  <div className="match-top" role="region" aria-label="Live match status"><div className="match-context"><span className="eyebrow">{hud.mapName?.toUpperCase()} / {hudRoute}</span><strong>{hud.modeName?.toUpperCase()}</strong><small className="phase-label">PHASE / {phase}</small>{isTeamMode(hudMode)&&<small className="team-label">{teamName(player.team)} TEAM · {hud.spectate?'FOLLOWING':'YOU'}</small>}</div><div className="match-clock" aria-label={`${hud.spectate?'Spectating':`${clock(hud.config.timeLimit-hud.time)} remaining`}`}><strong>{hud.spectate?'SPECTATING':clock(hud.config.timeLimit-hud.time)}</strong><small>{hud.net?'NETWORK MATCH':hud.config.botCount===0?'SOLO PRACTICE':armsrace?ladderStatus(player,WEAPONS.length).label:`FIRST TO ${hud.config.fragLimit} ${modeGoal(hudMode).toLowerCase()}`}</small></div><div className="frag-counter"><strong>{armsrace?ladderStatus(player,WEAPONS.length).rung+1:isTeamMode(hudMode)?teamScoreText(hud.teamScores??hud.teams)||player.frags:player.frags}<span>{hud.spectate?'':` / ${armsrace?WEAPONS.length:hud.config.fragLimit}`}</span></strong><small>{hud.spectate?`FOLLOWING ${player.name.toUpperCase()}`:armsrace?'LADDER RUNG':isTeamMode(hudMode)?modeGoal(hudMode):'YOUR FRAGS'}</small></div></div>
  {hud.spectate&&hud.net&&runtime.current&&<button type="button" className="spectator-return" onClick={()=>changeMode('lobby')}>RETURN TO LOBBY</button>}
  {hud.spectateLocal&&runtime.current&&<div className="spectate-cam-panel" role="status"><span className="eyebrow">SPECTATE BOTS</span><strong>{(CAMERA_MODE_LABELS as any)[runtime.current?.cameraMode]||String(runtime.current?.cameraMode||'auto').toUpperCase()}</strong><small>B CYCLE CAMERA · [ / ] FOLLOW BOT · F FREE CAM{runtime.current?.cameraMode==='free'?' · WASD / SPACE / SHIFT / CTRL':''}</small></div>}
  {isSingle&&<SinglePlayerHud single={single}/>}
  {announcement==='kill'&&<div className={`kill-banner ${killNotice.kind}`} role="status" aria-live="polite">{killNotice.text}</div>}
  {announcement==='callout'&&<div className={`kill-callout ${hud.killCue.kind}`} role="status" aria-live="polite"><strong>{hud.killCue.text}</strong><small>{hud.killCue.detail}</small></div>}
  {announcement==='sudden'&&<div className="objective-announcer sudden-death" role="status" aria-live="polite"><strong>{suddenBanner.text}</strong><small>{suddenBanner.detail}</small></div>}
  {announcement==='start'&&<div className="objective-announcer start" role="status" aria-live="polite"><strong>{startBanner.text}</strong><small>{startBanner.detail}</small></div>}
  {announcement==='score'&&<div className={`objective-announcer ${scoreCue.kind}`} role="status" aria-live="polite"><strong>{scoreCue.text}</strong>{scoreCue.amount>1&&<small>{scoreCue.amount}×</small>}</div>}
  {!isSingle&&<section className="command-panel" aria-label="Current objective and next action"><div className="command-kicker"><span className="accent-line"/> LIVE COMMAND <b>{phase}</b></div><div className="command-copy"><h2>{brief.title}</h2><p>{brief.action}</p></div><div className="command-meta"><span><small>OBJECTIVE</small><strong>{brief.detail}</strong></span><span><small>MAP ROUTE</small><strong>{hudMap?.tag??hud.mapName} / {hudRoute}</strong></span>{(isTeamMode(hudMode)||hudMode?.id==='armsrace')&&<span><small>{hudMode?.id==='ctf'?'FLAG STATE':hudMode?.id==='armsrace'?'NEXT UP':'CONTROL STATUS'}</small><strong>{hudMode?.id==='ctf'?flagText(hud):brief.status}</strong></span>}</div>{hud.captureNotice&&<b className="command-alert">{hud.captureNotice}</b>}</section>}<div className="visually-hidden" role="status" aria-live="polite">{hud.modeName}. {brief.title}. {brief.action}. {brief.status||brief.detail}</div>
  {hud.caption&&<div className="audio-caption" role="status" aria-live="polite">{hud.caption}</div>}
  {display.showKillFeed!==false&&<div className="kill-feed" role="log" aria-live="polite" aria-relevant="additions" aria-label="Kill feed">{hud.feed?.filter((e:any)=>hud.time-e.time<6).map((e:any,i:number)=><div key={`${e.time}-${i}`}><span>{e.killer}</span><Crosshair size={12}/>{killFeedWeapon(e,WEAPONS)&&<small>{killFeedWeapon(e,WEAPONS)}</small>}<span>{e.victim}</span>{e.self&&<small>SELF</small>}</div>)}</div>}
  {!hud.spectate&&display.showRadar!==false&&<div className="radar" aria-hidden="true"><svg viewBox="-1.18 -1.18 2.36 2.36" role="presentation"><circle className="radar-ring" r="1"/><circle className="radar-ring" r=".5"/><line className="radar-axis" x1="-1" y1="0" x2="1" y2="0"/><line className="radar-axis" x1="0" y1="-1" x2="0" y2="1"/><polygon className="radar-view" points="0,-.18 -.11,.12 .11,.12"/><line className="radar-sweep" x1="0" y1="0" x2="0" y2="-1"/>{radar.contacts.map((c:any,i:number)=>{const b:any=radarBlip(c,player,radarCols);if(b.shape==='circle')return <circle key={`a${c.id}`} cx={b.cx} cy={b.cy} r={b.r} fill={b.fill} className={`${b.dead?'radar-dead':''} ${b.revealed?'radar-revealed':''}`}/>;if(b.shape==='rect')return <g key={`z${c.id}`}><rect x={b.rect.x} y={b.rect.y} width={b.rect.width} height={b.rect.height} fill={b.fill}/>{b.label&&<text className="radar-zone-label" x={b.cx} y={b.cy} textAnchor="middle" dominantBaseline="central" fill={b.fill}>{b.label}</text>}</g>;if(b.shape==='payload'){const circ=2*Math.PI*b.ring.r;return <g key="payload"><circle cx={b.cx} cy={b.cy} r={b.ring.r} fill="none" stroke={b.fill} strokeWidth={b.ring.thickness} strokeDasharray={`${(b.progressRatio??0)*circ} ${circ}`} transform={`rotate(-90 ${b.cx} ${b.cy})`} className={b.clamped?'radar-revealed':''}/><rect x={b.cx-.05} y={b.cy-.05} width=".1" height=".1" fill={b.fill}/>{b.delivered&&<circle cx={b.cx} cy={b.cy} r=".026" fill="#fff"/>}</g>;}return <polygon key={`f${b.team??'n'}-${c.index??i}`} points={b.points} fill={b.fill}/>;})}</svg></div>}
  {hud.spectate&&<div className="spectator-board" role="group" aria-label="Spectator targets">{spectatorBoard(hud.actors,runtime.current?.spectateTarget).map((a:any)=><button type="button" key={a.id} className={a.current?'current':''} aria-pressed={a.current} onClick={()=>{const r=runtime.current;if(!r)return;r.spectateTarget=a.id;r.view.setSpectatorTarget(a.id);}}><span>{a.name}</span><small>{a.team!==undefined&&a.team!==null?`TEAM ${a.team+1}`:'FREE'}</small></button>)}</div>}
  {hud.spectate?<div className="spectator-tag"><span className="eyebrow">SPECTATOR MODE</span><h2>NO SEAT</h2><p>Camera follows {player.name} live. Snapshot feed only — no inputs sent.</p></div>:player.health>0?<><div className={`crosshair shape-${display.crosshair}`} style={{'--crosshair-color':display.color,'--crosshair-size':display.size,'--crosshair-gap':`${crosshairGap}px`} as any}><span/><span/><span/><span/></div>{marker&&<div className={`hitmarker ${marker}`} role="status" aria-live="polite" aria-label={marker==='kill'?'Elimination confirmed':'Hit confirmed'}><span/><span/></div>}{reloading&&<div className="reload-indicator" role="status" aria-live="polite" aria-label={`Reloading ${Math.round(reloadFill*100)} percent`}><span className="reload-label">RELOADING</span><span className="reload-track"><i style={{width:`${Math.round(reloadFill*100)}%`}}/></span></div>}{posture&&<div className="posture-chip" role="status">{posture}</div>}</>:<div className="death-message"><span className="eyebrow">CONNECTION LOST</span><h2>RECOMPILING</h2><p>Respawning in {Math.max(1,Math.ceil(player.dead))}…</p></div>}
  {hud.damage&&!hud.spectate&&<div className="damage-vignette"/>}
  {display.showDamageNumbers!==false&&hud.damageNumbers?.length?<div className="damage-numbers" aria-hidden="true">{hud.damageNumbers.map((n:any)=>{const fade=damageNumberStyle((performance.now()-n.born)/1000,{reduced:reducedMotion()});return <span key={n.id} className={`damage-number ${n.kill?'kill':'hit'}`} style={{left:`${n.x}px`,top:`${n.y}px`,opacity:fade.opacity,transform:`translate(-50%,-50%) translateY(${fade.dy}px)`}}>{n.amount}</span>;})}</div>:null}
  {damageIndicator&&!hud.spectate&&(damageIndicator.hasSource?<div className="damage-direction" style={{'--damage-angle':`${-damageIndicator.angle}rad`} as any} aria-hidden="true"><i/></div>:<div className="damage-flash" aria-hidden="true"/>)}
  <div className="hud-lower"><div className="hud-messages"><div className="pickup-message">{player.slow>0?`CONTEXT JAM · ${player.slow.toFixed(1)}s`:Object.entries(player.powerups??{}).filter(([,seconds]:any)=>seconds>0).map(([id,seconds]:any)=>`${id.toUpperCase()} · ${seconds.toFixed(1)}s`).join('  ·  ')||hud.pickup}</div>
  {player.protection>0&&player.health>0&&!hud.spectate&&<div className="spawn-protection"><Shield size={15}/> SPAWN PROTECTION</div>}
  {vehiclePrompt&&<div className="vehicle-prompt">{vehiclePrompt}</div>}
  {!vehicle&&!hud.spectate&&player.health>0&&(ammoEmpty||ammoLow)&&<div className={`ammo-warning ${ammoLow&&!ammoEmpty?'pulse':''}`}>{ammoEmpty?'OUT OF AMMO':'LOW AMMO'} / {player.ammo[player.weapon]} LEFT / 1-9/0 OR WHEEL TO SWITCH</div>}
  {pointerHint&&runtime.current&&!hud.spectate&&!chatOpen&&!touchControls&&<div className="pointer-hint">Click the arena to capture your mouse. WASD moves; hold left mouse to aim if capture is unavailable. <button onClick={requestLock}>Capture mouse</button></div>}
  </div>
  <div className="bottom-hud"><div className="vitals"><div className="health"><span>+</span><strong>{Math.ceil(player.health)}</strong><small>{hud.spectate?'WATCHED':`HEALTH / ${player.maxHealth??100}`}</small></div><div className="armor"><Shield size={22}/><strong>{Math.ceil(player.armor)}</strong><small>ARMOR</small></div><div className="health-track"><i style={{width:`${Math.max(0,Math.min(100,100*player.health/(player.maxHealth??100)))}%`}}/></div></div><>{!hud.spectate&&grenadeStatus(player)&&<div className={`grenade-chip ${grenadeStatus(player).ready?'ready':''}`} role="status"><b>G</b><span>{grenadeStatus(player).label}</span></div>}{!hud.spectate&&hud.config?.mode==='armsrace'&&<div className="ladder-chip" role="status"><b>ARS</b><span>{ladderStatus(player,WEAPONS.length).label}</span></div>}{!hud.spectate&&streakStatus(player)&&<div className="streak-chip" role="status"><b>×</b><span>{streakStatus(player)?.label}</span></div>}</>{!hud.spectate&&<div className={`ability-hud ${player.active>0?'active':''}`}><span className="ability-q">Q</span>{powerIcon(player.harness,25)}<div><strong>{activePower?.power}</strong><small>{vehicle?'UNAVAILABLE WHILE DRIVING':hud.config.mode==='instagib'?'DISABLED IN INSTAGIB':player.active>0?`ACTIVE · ${player.active.toFixed(1)}s`:player.cooldown>0?`RECHARGING · ${player.cooldown.toFixed(1)}s`:'ABILITY READY'}</small></div><div className="cooldown-track"><i style={{width:`${100*(1-player.cooldown/((activePower?.cooldown||1)*(hud.config.fastPowers?.5:1)))}%`}}/></div></div>}{!hud.spectate&&player.health>0&&(vehicle?<div className={`weapon-hud vehicle-hud ${vehicle.overheated?'overheated':''}`}><div className="weapon-slots"><span>PUMA / {Math.ceil(vehicle.health)} / {vehicle.maxHealth} HP</span></div><div><strong>{Math.round(Math.max(0,Math.min(1,vehicle.heat))*100)}%</strong><span>MOUNTED CHAINGUN<small>{vehicle.overheated?'OVERHEATED / COOLING':'HEAT'}</small></span></div></div>:<div className="weapon-hud"><div className="weapon-slots">{WEAPONS.map((w:any,i:number)=><span key={w.name} className={`${player.weapon===i?'equipped':''} ${player.ammo[i]===0?'unavailable':''}`}>{i+1} {w.short}</span>)}</div><div><strong>{ammoText(player.ammo[player.weapon])}</strong><span>{WEAPONS[player.weapon].name}{weaponTag(WEAPONS[player.weapon])&&<b className="weapon-tag">{weaponTag(WEAPONS[player.weapon])}</b>}<small>{player.reloading?'RELOADING':ammoText(player.ammo[player.weapon])==='∞'?'UNLIMITED AMMO':'AMMUNITION'}</small></span></div></div>)}</div>
  </div>
  <div className="hud-bottom-note"><span>TAB / SCOREBOARD</span>{hud.spectate&&<span>[ / ] FOLLOW</span>}{hud.net&&hud.quality&&<span className={`net-quality ${hud.quality.tone}`}>{hud.quality.label} · {hud.quality.ms}MS</span>}{voiceHint(voiceState.enabled,voiceState.mode)&&<span>{voiceHint(voiceState.enabled,voiceState.mode)}</span>}{display.showFps&&<span>{hud.fps||0} FPS · {hud.renderer==='software'?'CPU':'WEBGL'}</span>}<span>{escapeHint(hud.net)}</span></div></div>;
}
